apiVersion: v1
kind: Pod
metadata:
  name: gcloudkubectl
spec:
  serviceAccountName: jenkins
  containers:
    - name: gcloud
      image: gcr.io/cloud-builders/gcloud
      command: ['cat']
      tty: true
    - name: kubectl
      image: gcr.io/cloud-builders/gcloud
      command: ['cat']
      tty: truesss